version: "3.8"

services:
  tsalpha:
    # avoid weird problems with container/host DNS resolver
    dns: 8.8.8.8
    build:
      context: ./dockerfiles
      args:
        uid: "${HOST_UID}"
    image: tsalpha
    user: "${HOST_UID}:${HOST_GID}"
    volumes:
      # Mount code in working dir
      - .:/app
    working_dir: /app
