version: "3.8"

services:
  web:
    image: caddy:2.4.5
    ports:
      - "8000:80"
    volumes:
      - .:/app
      - ./Caddyfile:/etc/caddy/Caddyfile
      # persistent data for caddy
      - web_data:/data

  tsalpha:
    # avoid weird problems with container/host DNS resolver
    dns: 8.8.8.8
    build: ./dockerfiles
    image: tsalpha
    user: "${UID_GID}"
    volumes:
      # Mount code in working dir
      - .:/app
    working_dir: /app

  db:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ts_alpha
      MYSQL_DATABASE: ts_alpha
      MYSQL_USER: ts_alpha
      MYSQL_PASSWORD: ts_alpha
    volumes:
      - db_data:/var/lib/db_data

volumes:
  web_data:
  db_data:
